name: dynamic_nested_bottom_sheets
description: "A highly customizable, easy-to-use Flutter package for building dynamic, nested modal bottom sheets with support for snapping, stackable sheets, custom backgrounds, adjustable barrier color and dismiss behavior, and much more!"
version: 0.0.1
homepage: https://github.com/Usama-Ali1358/dynamic_nested_bottom_sheets.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


